# Site settings 配置站点
title: 'Samaritan Manasseh - Simon Blog'
description: 'thanks to the light you shower around me.'
keyword: 'Simon,Philosophy,Books,Read,Develop,Music,Photography,Design'
url: 'https://rsp.ink' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2013

# Author 配置博主信息
author: 'Simon.J.R'
nickname: 'Simon'
bio: 'thanks to the light you shower around me.'
avatar: '/assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: true
  disqus_url: 'https://rspstudio.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, , seaOfClouds
postPatterns: 'ticTacToe'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:i@rsp.ink'
  instagram: 'https://www.instagram.com/monihuanhua/'
  facebook: 'https://www.facebook.com/lpsrsp'
  medium: 'https://matters.news/@imrsp'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 5
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
